apiVersion: v1
kind: Pod
metadata:
  name: mc2
spec:
  containers:
  - name: producer
    image: kubebox85/producer-consumer
    command: ["/bin/sh","-c"]
    args: ["sleep 10 && ./ipc -producer"] 

  - name: consumer
    image: kubebox85/producer-consumer
    command: ["./ipc", "-consumer"]
  restartPolicy: Never
