apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  containers:
  - name: web
    image: nginx

  initContainers:
  - name: 1stcontainer
    image: alpine
    command: ['sleep', '60']

  - name: 2ndcontainer
    image: ubuntu
    command: ['sleep', '50']
